#!/bin/sh
# Copyright (C) 2012-2014 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>
# 	Author: AHMED Zribi <ahmed.zribi@pivasoftware.com>

common_get_parameter_notification() {
	local _dest="$1"
	local _parm="$2"
	local _val=0
	local p ntype len maxlen=0
	
	for ntype in "active:2" "passive:1" "none:0"; do
		local list_notif=`$UCI_GET easycwmp.@notifications[0].${ntype%:*}`
		for p in $list_notif; do
			if [ "$p" = "$_parm" ]; then
				_val=${ntype#*:}
				eval "export -- \"$_dest=$_val\""
				return
			fi
			case $p in
				*.)
				case $_parm in
					$p*)
					len=${#p}
					if [ $len -gt $maxlen ]; then
						_val=${ntype#*:}
						maxlen=$len
					fi
				esac
				;;
			esac
		done
	done
	eval "export -- \"$_dest=$_val\""
}

common_remove_parameter_notification() {
	local _parm="$1"
	local ntype
	for ntype in active passive none; do
		case $_parm in
			*.)
			local list_del=`$UCI_GET easycwmp.@notifications[0].$ntype`
			local del
			for del in $list_del; do
				case $del in
					$_parm*)
					$UCI_DEL_LIST easycwmp.@notifications[0].$ntype=$del 2>/dev/null
					;;
				esac
			done
			;;
			*)
			$UCI_DEL_LIST easycwmp.@notifications[0].$ntype=$_parm 2>/dev/null
			;;
		esac
	done
}

common_set_parameter_notification() {
	local _parm="$1"
	local _val="$2"
	local tmp=`$UCI_GET easycwmp.@notifications[0] 2>/dev/null`
	if [ "$tmp" = "" ]; then
		$UCI_ADD easycwmp notifications 2>&1 >/dev/null
	else
		common_remove_parameter_notification $_parm
	fi
	local notif
	common_get_parameter_notification notif $_parm
	[ "$notif" = "$_val" ] && return
	if [ "$_val" -eq "1" ]; then
		$UCI_ADD_LIST easycwmp.@notifications[0].passive="$_parm" 2>&1 >/dev/null
	elif [ "$_val" -eq "2" ]; then
		$UCI_ADD_LIST easycwmp.@notifications[0].active="$_parm" 2>&1 >/dev/null
	elif [ "$_val" -eq "0" ]; then
		local list_prm="`$UCI_GET easycwmp.@notifications[0].active` `$UCI_GET easycwmp.@notifications[0].passive`"
		for prm in $list_prm; do
			case $prm in
				*.)
				case $_parm in
					$prm*)
					$UCI_ADD_LIST easycwmp.@notifications[0].none="$_parm" 2>&1 >/dev/null
					break
					;;
				esac
				;;
			esac
		done
	fi
}

common_delay_service_restart_in_apply_service() {
local service="$1"
local delay="$2"
[ "`cat $apply_service_tmp_file 2>/dev/null | grep /etc/init.d/$service`" != "" ] && return
cat >> "$apply_service_tmp_file" <<EOF
/etc/init.d/$service stop >/dev/null 2>/dev/null
sleep $delay
/etc/init.d/$service start >/dev/null 2>/dev/null
EOF
}

common_execute_command_in_apply_service() {
local command="$1"
local chk=`cat "$apply_service_tmp_file" 2>/dev/null | grep "^$command "`
[ "$chk" != "" ] && return
cat >> "$apply_service_tmp_file" <<EOF
$command >/dev/null 2>/dev/null
EOF
}

common_set_parameter_fault() {
	local _parm="$1"
	local _fault="$2"
	common_json_output_fault "$_parm" "$_fault" >> $set_fault_tmp_file
}

common_get_inform_deviceid()
{
	local msg

	json_init
	json_add_string "manufacturer" "`$UCI_GET easycwmp.@device[0].manufacturer 2> /dev/null`"
	json_add_string "oui" "`$UCI_GET easycwmp.@device[0].oui 2> /dev/null`"
	json_add_string "product_class" "`$UCI_GET easycwmp.@device[0].product_class 2> /dev/null`"
	json_add_string "serial_number" "`$UCI_GET easycwmp.@device[0].serial_number 2> /dev/null`"

	json_close_object
	local msg=`json_dump`
	echo "$msg"
}

common_easycwmp_config_load() {
	easycwmp_config_changed="1"
}

case_param() {
	[ -z "$1" ] && return 0
	[ "${3/$1/}" != "$3" -o "${1/$3/}" != "$1" ] && return 0
	return $E_INVALID_PARAMETER_NAME
}

common_set_bool() {
	local cfg="$1"
	local val="$2"
	local true="$3"
	local false="$4"
	val=`echo "$val" | tr '[A-Z]' '[a-z]'`
	if [ "$val" = "true" -o "$val" = "1" ]; then
		$UCI_SET $cfg=$true
	elif [ "$val" = "false" -o "$val" = "0" ]; then
		$UCI_SET $cfg=$false
	else
		return $E_INVALID_PARAMETER_VALUE
	fi
	return 0
}

##### common entries called by easycwmp.sh #####
common_entry_get_value() {
	local param="$1"
	g_fault_code=$E_INVALID_PARAMETER_NAME
	local entry method=""
	local tmp=" $prefix_list "
	if [ -z "$param" -o "${tmp/ $param /}" != "$tmp" ]; then method="common_get_value"; g_fault_code=0
	elif [ "${param%.}" != "$param" ]; then method="common_get_value_inparam_isobj_check"
	else method="common_get_value_inparam_isparam_check"
	fi
	
	for entry in $entry_execute_method_list; do
		$entry "$param" "$method"
	done
	return $g_fault_code
}

common_entry_get_name() {
	local param="$1"
	local nextlevel="$2"
	g_fault_code=$E_INVALID_PARAMETER_NAME
	local entry method=""
	local tmp=" $prefix_list "
	
	if [ -z "$param" -a "$nextlevel" = "1" ]; then
		entry_execute_method_root "" "common_get_name" "1"
		return 0
	fi
	if [ -z "$param" -o "${tmp/ $param /}" != "$tmp" ]; then 
		if [ "$nextlevel" = "0" ]; then
			g_fault_code=0
			method="common_get_name"
		else 
			method="common_get_name_inparam_isobj_check"
		fi
	elif [ "${param%.}" != "$param" ]; then method="common_get_name_inparam_isobj_check"
	else method="common_get_name_inparam_isparam_check"
	fi
	
	for entry in $entry_execute_method_list; do
		$entry "$param" "$method" "$nextlevel"
	done
	return $g_fault_code
}

common_entry_get_notification() {
	local param="$1"
	g_fault_code=$E_INVALID_PARAMETER_NAME
	local entry method=""
	local tmp=" $prefix_list "
	if [ -z "$param" -o "${tmp/ $param /}" != "$tmp" ]; then method="common_get_notification"; g_fault_code=0
	elif [ "${param%.}" != "$param" ]; then method="common_get_notification_inparam_isobj_check"
	else method="common_get_notification_inparam_isparam_check"
	fi
	
	for entry in $entry_execute_method_list; do
		$entry "$param" "$method"
	done
	return $g_fault_code
}

common_entry_set_value() {
	local param="$1"
	local val="$2"
	local entry method="common_set_value_check"

	[ -z "$param" -o "${param%.}" != "$param" ] && return $E_INVALID_PARAMETER_NAME
	
	for entry in $entry_execute_method_list; do
		$entry "$param" "$method" "$val"
	done
	return $E_INVALID_PARAMETER_NAME
}

common_entry_set_notification() {
	local param="$1"
	local notification="$2"
	local entry method="common_set_notification_check"

	[ -z "$param" ] && return $E_NOTIFICATION_REJECTED
	for entry in $entry_execute_method_list; do
		$entry "$param" "$method" "$notification"
	done
	return $E_INVALID_PARAMETER_NAME
}

common_entry_inform() {
	local entry method="common_inform_check"
	for entry in $entry_execute_method_list; do
		$entry "" "$method"
	done
	return 0
}

common_entry_add_object() {
	local param="$1"
	local entry
	
	for entry in $entry_add_object_list; do
		$entry "$param"
		local e="$?"
		[ "$e" != "0" ] && continue;
		common_set_parameter_notification "$param$instance." "0"
		return 0
	done
	return $E_INVALID_PARAMETER_NAME
}

common_entry_delete_object() {
	local param="$1"
	local entry
	
	for entry in $entry_delete_object_list; do
		$entry "$param"
		local e="$?"
		[ "$e" != "0" ] && continue;
		common_remove_parameter_notification "$param"
		return 0
	done
	return $E_INVALID_PARAMETER_NAME
}
##### common execute methods #####

common_execute_method_obj() {
	local inparam="$1"
	local method="$2"
	local arg="$3"
	local refparam="$4"
	local permission="$5"
	
	"$method""_obj" "$arg" "$inparam" "$refparam" "$permission"
}

common_execute_method_param() {
	local inparam="$1"
	local method="$2"
	local arg="$3"
	local refparam="$4"
	local permission="$5"
	local getcmd="$6"
	local setcmd="$7"
	local type="$8"
	local forcedinform="$9"
	
	"$method""_param" "$arg" "$inparam" "$refparam" "$permission" "$getcmd" "$setcmd" "$type" "$forcedinform"
}
##### get value #####
common_get_value_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	local val=`$getcmd`
	common_json_output_get_value "$refparam" "$val" "$type"
	return 0
}

common_get_value_obj() {
	return 0
}

common_get_value_inparam_isparam_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	local val=`$getcmd`
	common_json_output_get_value "$refparam" "$val" "$type"
	exit 0
}

common_get_value_inparam_isparam_check_obj() {
	return $E_INVALID_PARAMETER_NAME
}

common_get_value_inparam_isobj_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	case "$refparam" in "$inparam"*)
		local val=`$getcmd`
		common_json_output_get_value "$refparam" "$val" "$type"
		g_fault_code=0
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

common_get_value_inparam_isobj_check_obj() {
	case "$refparam" in "$inparam"*)
		g_fault_code=0
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

##### get name #####
common_get_name_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	common_json_output_get_name "$refparam" "$permission"
	return 0
}

common_get_name_obj() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	
	common_json_output_get_name "$refparam" "$permission"
	return 0
}

common_get_name_inparam_isparam_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"

	local nextlevel="$arg"
	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	[ "$nextlevel" = "1" ] && exit $E_INVALID_ARGUMENTS

	common_json_output_get_name "$refparam" "$permission"
	exit 0
}

common_get_name_inparam_isparam_check_obj() {
	return $E_INVALID_PARAMETER_NAME
}

common_get_name_inparam_isobj_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	case "$refparam" in "$inparam"*)
		g_fault_code=0
		if [ "$nextlevel" = "0" -o "${refparam%.*}." = "$inparam" ]; then
			common_json_output_get_name "$refparam" "$permission"
			return 0;
		fi
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

common_get_name_inparam_isobj_check_obj() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
		
	case "$refparam" in "$inparam"*)
		g_fault_code=0
		if [ "$nextlevel" = "0" -o "${refparam%.*.}." = "$inparam" ]; then
			common_json_output_get_name "$refparam" "$permission"
			return 0;
		fi
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

##### get notification #####
common_get_notification_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	local notification=""
	common_get_parameter_notification "notification" "$refparam"
	common_json_output_get_notification "$refparam" "$notification"
	return 0
}

common_get_notification_obj() {
	return 0
}

common_get_notification_inparam_isparam_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	local notification=""
	common_get_parameter_notification "notification" "$refparam"
	common_json_output_get_notification "$refparam" "$notification"
	exit 0
}

common_get_notification_inparam_isparam_check_obj() {
	return $E_INVALID_PARAMETER_NAME
}

common_get_notification_inparam_isobj_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	case "$refparam" in "$inparam"*)
		local notification=""
		common_get_parameter_notification "notification" "$refparam"
		common_json_output_get_notification "$refparam" "$notification"
		g_fault_code=0
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

common_get_notification_inparam_isobj_check_obj() {
	case "$refparam" in "$inparam"*)
		g_fault_code=0
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

##### set value #####
common_set_value_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	local val="$arg"
	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	[ "$permission" != "1" -o -z "$setcmd" ] && exit $E_NON_WRITABLE_PARAMETER
	echo "$refparam $setcmd \"$val\"" >> $set_command_tmp_file
	exit 0
}

common_set_value_check_obj() {
	return $E_INVALID_PARAMETER_NAME
}

##### set notification #####
common_set_notification_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	local notification="$arg"
	common_set_parameter_notification "$refparam" "$notification"
	exit 0
}

common_set_notification_check_obj() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"

	[ "$inparam" != "$refparam" ] && return $E_INVALID_PARAMETER_NAME
	local notification="$arg"
	common_set_parameter_notification "$refparam" "$notification"
	exit 0
}

##### inform #####
common_inform_check_param() {
	local arg="$1"
	local inparam="$2"
	local refparam="$3"
	local permission="$4"
	local getcmd="$5"
	local setcmd="$6"
	local type="$7"
	local forcedinform="$8"
	
	[ -z "$forcedinform" ] && return $E_INVALID_PARAMETER_NAME
	local val=`$getcmd`
	common_json_output_get_value "$refparam" "$val" "$type"
	return 0
}

common_inform_check_obj() {
	return $E_INVALID_PARAMETER_NAME
}

##### json output #####
common_json_output_get_value() {
	local parameter="$1"
	local value="$2"
	local type="$3"

	json_init
	json_add_string "parameter" "$parameter"
	json_add_string "value" "$value"
	[ -n "$type" ] && json_add_string "type" "$type"
	json_close_object
	local msg=`json_dump`
	echo "$msg"
}

common_json_output_get_name() {
	local parameter="$1"
	local permission="$2"

	json_init
	json_add_string "parameter" "$parameter"
	json_add_string "writable" "$permission"
	json_close_object
	local msg=`json_dump`
	echo "$msg"
}

common_json_output_get_notification() {
	local parameter="$1"
	local notification="$2"

	json_init
	json_add_string "parameter" "$parameter"
	json_add_string "notification" "$notification"
	json_close_object
	local msg=`json_dump`
	echo "$msg"
}

common_json_output_fault() {
	local parameter="$1"
	local fault_code="$2"
	
	json_init
	[ -n "$parameter" ] && json_add_string "parameter" "$parameter"
	json_add_string "fault_code" "$fault_code"
	json_close_object
	local msg=`json_dump`
	echo "$msg"
}

common_json_output_status() {
	local status="$1"
	local instance="$2"
	
	json_init
	json_add_string "status" "$status"
	[ -n "$instance" ] && json_add_string "instance" "$instance"
	[ "$easycwmp_config_changed" = "1" ] && json_add_string "config_load" "1"
	json_close_object
	local msg=`json_dump`
	echo "$msg"
}
