#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.ManagementServer."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_ManagementServer"

entry_execute_method_root_ManagementServer() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.ManagementServer."*)
		common_execute_method_obj "$1" "$2" "$3" "$DMROOT.ManagementServer." "0"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.URL" "1" "management_server_get_url" "management_server_set_url"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.Username" "1" "$UCI_GET easycwmp.@acs[0].username" "management_server_set easycwmp.@acs[0].username"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.Password" "1" "" "management_server_set easycwmp.@acs[0].password"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.PeriodicInformEnable" "1" "$UCI_GET easycwmp.@acs[0].periodic_enable" "management_server_set easycwmp.@acs[0].periodic_enable" "xsd:boolean"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.PeriodicInformInterval" "1" "$UCI_GET easycwmp.@acs[0].periodic_interval" "management_server_set easycwmp.@acs[0].periodic_interval" "xsd:unsignedInt"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.PeriodicInformTime" "1" "$UCI_GET easycwmp.@acs[0].periodic_time" "management_server_set easycwmp.@acs[0].periodic_time" "xsd:dateTime" 
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.ConnectionRequestURL" "0" "management_server_get_connection_request_url" "" "" "1"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.ConnectionRequestUsername" "1" "$UCI_GET easycwmp.@local[0].username" "management_server_set easycwmp.@local[0].username"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.ConnectionRequestPassword" "1" "" "management_server_set easycwmp.@local[0].password"
		common_execute_method_param "$1" "$2" "$3" "$DMROOT.ManagementServer.ParameterKey" "0" "$UCI_GET easycwmp.@acs[0].parameter_key" "" "" "1"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################
management_server_get_url() {
	local scheme=`$UCI_GET easycwmp.@acs[0].scheme`
	local hostname=`$UCI_GET easycwmp.@acs[0].hostname`
	local port=`$UCI_GET easycwmp.@acs[0].port`
	local path=`$UCI_GET easycwmp.@acs[0].path`
	port=${port+:$port}
	echo "$scheme://$hostname$port$path"
}

management_server_set_url() {
	local val=$1
	local scheme
	local hostname
	local path
	local port
	
	local chk=`echo $val | grep "[a-zA-Z0-9_]\+://.*"`
	[ "$chk" = "" ] && return $E_INVALID_PARAMETER_VALUE

	scheme=${val%%://*}
	val=${val#*://}
	path=${val#*/}
	[ "$path" = "$val" ] && path="" || path="/$path"
	val=${val%%/*}
	port=${val#*:}
	[ "$port" = "$val" ] && port=""
	hostname=${val%%:*};
	
	$UCI_SET easycwmp.@acs[0].scheme=$scheme
	$UCI_SET easycwmp.@acs[0].hostname=$hostname
	$UCI_SET easycwmp.@acs[0].port=$port
	$UCI_SET easycwmp.@acs[0].path=$path
	common_easycwmp_config_load
	return 0
}

management_server_set() {
	local cfg=$1
	local val=$2
	$UCI_SET $cfg="$val"
	common_easycwmp_config_load
	return 0
}

management_server_get_connection_request_url() {
	local val
	if [ -z "$default_management_server_connection_request_url" ]; then
		local intf=`$UCI_GET easycwmp.@local[0].interface 2> /dev/null`
		local ip=`ifconfig "$intf" | grep inet | sed 's/^ *//g' | cut -f 2 -d ' '|cut -f 2 -d ':'`
		local port=`$UCI_GET easycwmp.@local[0].port 2> /dev/null`

		if [ -n "$ip" -a -n "$port" ]; then
			val="http://$ip:$port/"
		fi
	else
		val=$default_management_server_connection_request_url
	fi
	echo $val
}