#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=90

boot() {
        service_start /usr/sbin/easycwmpd --boot
}

start() {
        service_start /usr/sbin/easycwmpd --getrpcmethod
}

stop() {
        service_stop /usr/sbin/easycwmpd
}