#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=90

UCI_SET="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set"
UCI_COMMIT="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} commit"
init_device_info() {
	local val

	val=`cat "/etc/device_info" | grep "DEVICE_MANUFACTURER" | cut -f 2 -d '=' | sed "s/'//g"`
	[ -n "$val" ] && $UCI_SET easycwmp.@device[0].manufacturer=$val

	val=`cat "/etc/device_info" | grep "DEVICE_PRODUCT" | cut -f 2 -d '=' | sed "s/'//g"`
	[ -n "$val" ] && $UCI_SET easycwmp.@device[0].product_class=$val

	val=`cat "/etc/device_info" | grep "DEVICE_REVISION" | cut -f 2 -d '=' | sed "s/'//g"`
	[ -n "$val" ] && $UCI_SET easycwmp.@device[0].hardware_version=$val

	val=`cat "/etc/openwrt_version"`
	[ -n "$val" ] && $UCI_SET easycwmp.@device[0].software_version=$val
	
	#The same thing here for OUI and SerialNumber
	$UCI_COMMIT easycwmp
}

boot() {
	init_device_info
	service_start /usr/sbin/easycwmpd --boot
}

start() {
	init_device_info
	service_start /usr/sbin/easycwmpd --getrpcmethod
}

stop() {
	service_stop /usr/sbin/easycwmpd
}